### PR TITLE
SDX-1222 Upgrade to Django 1.11

### PR DESCRIPTION
**Pull request by olga-andreeva**
* MIDDLEWARE
* TEMPLATES
* AUDIT_LOG_API_AUTH_USER_MODEL has to be specified

### CODE REVIEW

**Review by mohsinhijazee — COMMENTED** [review]
Following test is failing for me `audit_log.tests.audit_log_tests.test_logging.TrackingChangesTest.test_logging_custom_user`

**Comment by olga-andreeva** [comment]
@mohsinhijazee what version of Django are you using? Mine is 1.11.3.

**Comment by mohsinhijazee** [comment]
@olga-andreeva I am also using Django 1.11.3 with Django REST Framework 3.5.1

**Review by muthan — APPROVED** [review]
looks fine for me

**Review by mohsinhijazee — APPROVED** [review]
Looks good!

**Pull request merged**
